export const verifiedDate = '2026-09-20';
export const topics = [
  { id:'foundation', name:'数制与误差', en:'Representation', icon:'binary', prerequisite:'二进制与基本代数', description:'先分清位模式、数值和精度，再讨论如何计算。', keywords:'补码 · 定点 · ULP', core:['intro','goldberg'], goals:['手算 8 位补码的取值范围与符号扩展。','用二进制说明 0.1 为什么不能精确表示。','区分绝对误差、相对误差与 ULP。'], next:'加法的进位与冗余表示，是理解部分积压缩和 SRT 商选择的共同基础。' },
  { id:'addition', name:'加法与部分积压缩', en:'Addition & reduction', icon:'plus', prerequisite:'数制与误差', description:'理解进位传播，也理解为什么可以暂时不传播进位。', keywords:'CPA · CSA · 压缩树', core:['addition','multiadd'], goals:['推导 generate / propagate 与进位关系。','验证三个操作数压缩为两行后的数值不变。','区分压缩树延迟与末级 CPA 延迟。'], next:'将多操作数求和应用到乘法部分积；Wallace 与 Dadda 是压缩调度问题。' },
  { id:'booth', name:'Booth 乘法器', en:'Signed multiplication', icon:'multiply', prerequisite:'补码、加法与部分积压缩', description:'从符号重编码走到部分积生成、修正与归约。', keywords:'Radix-2 / 4 · 部分积', core:['multiplication','booth'], goals:['从二进制权重推导 radix-4 的 0、±1、±2 编码。','手算负数与最小负数输入，检查扩展位宽。','画出重编码、部分积压缩、CPA 三段结构。'], next:'乘法器也是迭代逼近除法和浮点乘加的数据通路基础。1951 年原文是原始 Booth 算法，不等同于完整 radix-4 实现教程。' },
  { id:'division', name:'除法算法', en:'Division', icon:'divide', prerequisite:'冗余表示、加法、乘法', description:'沿逐位递推与迭代逼近两条路径，建立算法全貌。', keywords:'恢复 / 不恢复 · SRT · NR', core:['division','iterative'], goals:['逐步跟踪余数与商，验证 N = QD + R。','理解 SRT 的冗余商位与商选择所需的界。','推导倒数迭代 x′ = x(2 − Dx)，讨论初值与舍入。'], next:'先理解精确递推与收敛条件，再比较周期数、乘法器复用和商修正的代价。' },
  { id:'floating', name:'浮点运算', en:'Floating-point arithmetic', icon:'float', prerequisite:'数制误差、乘除法算法', description:'把格式、舍入和特殊值连到实际运算数据通路。', keywords:'IEEE 754 · GRS · FMA', core:['floating','handbook'], goals:['区分规格化数、非规格化数、无穷和 NaN。','解释 guard、round、sticky 位如何参与舍入。','构造 FMA 单次舍入与分开乘加结果不同的例子。'], next:'规格与误差边界明确后，才能评价位宽、融合及流水线的 PPA 取舍。旧教材需结合 IEEE 754-2019 查证标准细节。' },
  { id:'ppa', name:'浮点 PPA 优化', en:'Architecture & trade-offs', icon:'chip', prerequisite:'浮点语义、数据通路与流水线', description:'在相同精度与约束下，比较功耗、性能和面积。', keywords:'精度 · 共享 · 流水线', core:['fpnew','hardfloat'], goals:['固定格式、舍入、工艺、时序与活动率后再比较 PPA。','分别记录延迟、吞吐率、面积与每次操作能耗。','检查共享、融合、位宽变化后的精度和特殊值行为。'], next:'建议练习：以一个正确实现为基线，每次只改变一个微架构因素。论文测量结果只适用于其报告条件。' }
];

const authorsDA = 'Miloš D. Ercegovac · Tomás Lang';
const lecture = (id,title,subtitle,chapter,topic,summary,focus,tags) => ({ id,title,subtitle,authors:authorsDA,year:'2003 / 2004',type:'讲义',topic,source:'UCLA · 作者配套讲义',access:'免费 PDF',free:true,url:`https://web.cs.ucla.edu/digital_arithmetic/files/ch${chapter}.pdf`,evidence:'https://web.cs.ucla.edu/digital_arithmetic/viewgraphs_p.html',summary,focus,tags,reference:`Digital Arithmetic，Chapter ${chapter} 配套讲义。讲义署名版权 2003，教材 2004。`,note:'作者高校页面公开提供的配套讲义，并非整本教材。'});

export const resources = [
 lecture('intro','Introduction','数制与算术基础',1,'foundation','从数值表示、位权与冗余数制出发，为后续算术算法建立共同语言。','先读数制、带符号整数与冗余表示；配合小位宽手算。',['补码','定点','数制','冗余表示','入门']),
 {id:'goldberg',title:'What Every Computer Scientist Should Know About Floating-Point Arithmetic',subtitle:'理解浮点误差的经典起点',authors:'David Goldberg',year:'1991',type:'论文',topic:'foundation',source:'Oracle · 经许可转载',access:'免费全文',free:true,url:'https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html',summary:'围绕浮点表示、舍入误差和消去现象，建立判断数值计算是否可靠的基础。',focus:'第一遍聚焦 Rounding Error、ULPs、Guard Digits 和 Cancellation；标准细节以后续规范为准。',tags:['误差','ULP','舍入','浮点','数值分析'],reference:'ACM Computing Surveys，1991 年 3 月。Oracle 页面说明为经 ACM 许可的编辑转载。',note:'经典概念仍有学习价值，但文中 IEEE 标准讨论不是 2019 版规范。'},
 lecture('addition','Two-Operand Addition','两操作数加法与进位',2,'addition','从基本进位关系进入不同加法器结构，理解速度与硬件成本的来源。','推导进位方程，并比较串行进位与并行进位的结构。',['CPA','CLA','前缀加法器','进位','加法器']),
 lecture('multiadd','Multioperand Addition','多操作数加法与压缩',3,'addition','理解 carry-save 表示、压缩网络及最终进位传播加法。','先验证数值不变量，再追踪压缩层级与最终 CPA。',['CSA','Wallace','Dadda','压缩树','部分积','4:2']),
 lecture('multiplication','Multiplication','从乘法算法到部分积结构',4,'booth','将重编码、部分积生成和累加联系起来，形成完整的乘法器视角。','围绕带符号乘法和重编码阅读，手算 radix-4 的负部分积。',['Booth','radix-4','重编码','符号扩展','乘法器']),
 {id:'booth',title:'A Signed Binary Multiplication Technique',subtitle:'Booth 算法的原始论文',authors:'Andrew D. Booth',year:'1951',type:'论文',topic:'booth',source:'Oxford Academic · 出版方',access:'购买 / 机构访问',free:false,url:'https://academic.oup.com/qjmam/article-abstract/4/2/236/1874893',summary:'回到原始带符号二进制乘法算法，理解连续 1 的加减重编码思想。',focus:'与教材交叉阅读：分清原始 Booth 算法和后续 modified Booth / radix-4。',tags:['Booth','radix-2','经典论文','重编码'],reference:'The Quarterly Journal of Mechanics and Applied Mathematics，4(2)，236–240，1951。DOI: 10.1093/qjmam/4.2.236。',note:'出版方页面可核实书目信息；全文权限以出版方为准。'},
 lecture('division','Division by Digit Recurrence Method','恢复、不恢复与 SRT 除法',5,'division','从余数递推和商位选择理解逐位除法，逐步走向更高基数。','围绕递推关系、冗余商位与商选择区间阅读。',['SRT','恢复除法','不恢复除法','商选择','除法器']),
 lecture('iterative','Iterative Methods','倒数与除法的迭代逼近',7,'division','理解用乘法改善近似值的路线，并与逐位递推方法对照。','跟踪误差怎样随迭代变化，再考虑有限精度和最后的商修正。',['Newton-Raphson','Goldschmidt','倒数','收敛','除法器']),
 lecture('floating','Floating-point Arithmetic','浮点格式、算法与实现',8,'floating','将浮点表示、基本运算和实现结构连接起来，建立硬件阅读框架。','沿对阶、运算、规格化与舍入梳理加法路径，再阅读乘除法。',['浮点','IEEE 754','规格化','舍入','GRS']),
 {id:'handbook',title:'Handbook of Floating-Point Arithmetic',subtitle:'第二版 · 浮点计算系统参考',authors:'Jean-Michel Muller 等',year:'2018',type:'教材',topic:'floating',source:'Springer / Birkhäuser · 出版方',access:'购买 / 机构访问',free:false,url:'https://link.springer.com/book/10.1007/978-3-319-76526-6',summary:'系统学习浮点基础、算法及软硬件实现，并查阅精度扩展与验证方法。',focus:'建议先读基础定义与格式，再读基本运算算法和硬件实现两部分。',tags:['浮点','FMA','舍入','数值分析','教材'],reference:'第二版，Birkhäuser，2018。DOI: 10.1007/978-3-319-76526-6。',note:'基于 IEEE 754-2008 的系统参考；2019 版规范需另行核对。'},
 {id:'fpnew',title:'FPnew: An Open-Source Multi-Format Floating-Point Unit Architecture for Energy-Proportional Transprecision Computing',subtitle:'从多格式 FPU 研究精度与能效',authors:'Stefan Mach · Fabian Schuiki · Florian Zaruba · Luca Benini',year:'2020',type:'论文',topic:'ppa',source:'arXiv · 作者预印本',access:'开放全文',free:true,url:'https://arxiv.org/abs/2007.01530',summary:'以可配置、多格式浮点单元为案例，学习精度、并行度与硬件能效之间的取舍。',focus:'先看架构和配置，再核对实现工艺、供电、测试负载与比较基线。',tags:['FPnew','低精度','混合精度','PPA','SIMD','FPU'],reference:'arXiv:2007.01530，2020 年 7 月 3 日提交。',note:'本条标注预印本年份；论文数据不作为其他工艺或设计的性能保证。'},
 {id:'hardfloat',title:'Berkeley HardFloat',subtitle:'阅读可参数化的浮点 RTL',authors:'John R. Hauser',year:'Release 1 · 2019',type:'开源实现',topic:'ppa',source:'作者官网',access:'开源代码 / 文档',free:true,url:'https://www.jhauser.us/arithmetic/HardFloat.html',summary:'以 Verilog 浮点模块学习内部编码、运算与舍入阶段的接口划分。',focus:'从 recoded format 和舍入模块入手；观察共享舍入与多格式参数化的可能性。',tags:['Verilog','RTL','FMA','舍入','PPA','验证'],reference:'Berkeley HardFloat，Release 1（2019 年 7 月）。',note:'先阅读支持格式与参数约束，不能直接假定所有自定义 FP4 / FP8 格式都适用。'},
 {id:'digital',title:'Digital Arithmetic',subtitle:'贯穿整条学习路线的主参考书',authors:authorsDA,year:'2004',type:'教材',topic:'foundation',source:'UCLA · 作者教材主页',access:'书籍信息 / 免费配套',free:false,url:'https://web.cs.ucla.edu/digital_arithmetic/',summary:'将基础算法与硬件实现联系起来，适合作为乘法、除法和浮点运算的主线。',focus:'建议顺序为第 1、2、3、4、5、7、8 章；免费配套讲义已拆为独立学习条目。',tags:['教材','Booth','除法','浮点','体系'],reference:'Morgan Kaufmann / Elsevier，2004。ISBN: 9781558607989。',note:'链接为作者的教材与配套材料主页，不提供未经授权的整书副本。'},
 {id:'modern',title:'Modern Computer Arithmetic',subtitle:'任意精度算法的理论补充',authors:'Richard P. Brent · Paul Zimmermann',year:'2010',type:'教材',topic:'division',source:'arXiv · 作者书稿',access:'开放书稿',free:true,url:'https://arxiv.org/abs/1004.4710',summary:'从任意精度算法角度补充整数、除法与浮点计算的复杂度认识。',focus:'按需要阅读整数算术与浮点算术部分，区分渐近复杂度和固定位宽电路成本。',tags:['教材','任意精度','除法','复杂度','算法'],reference:'arXiv:1004.4710，version 0.5.1，2010。',note:'这是正式出版前的作者书稿；主要面向软件算法，不是 RTL 或硬件架构教材。'},
 {id:'wallace',title:'A Suggestion for a Fast Multiplier',subtitle:'Wallace 压缩树的经典论文',authors:'C. S. Wallace',year:'1964',type:'论文',topic:'addition',source:'IEEE Xplore · 出版方',access:'购买 / 机构访问',free:false,url:'https://ieeexplore.ieee.org/document/4038071/',summary:'从经典组合乘法器设计出发，理解多行部分积的快速归约思想。',focus:'与多操作数加法讲义对照，区分压缩策略、末级加法器和布线代价。',tags:['Wallace','压缩树','部分积','乘法器','经典论文'],reference:'IEEE Transactions on Electronic Computers，EC-13(1)，14–17，1964。DOI: 10.1109/PGEC.1964.263830。',note:'书目由 IEEE 检索记录核实；出版方页面可能要求浏览器验证或机构权限。'},
 {id:'ieee',title:'IEEE Standard for Floating-Point Arithmetic',subtitle:'IEEE 754-2019 · 语义核对入口',authors:'IEEE',year:'2019',type:'标准',topic:'floating',source:'IEEE Standards Association',access:'购买 / 机构访问',free:false,url:'https://standards.ieee.org/ieee/754/6210/',summary:'用于核对浮点格式、运算结果、异常及舍入的规范要求。',focus:'以设计实际声称支持的格式和操作为范围，建立需要遵循的行为清单。',tags:['IEEE 754','标准','舍入','异常','NaN'],reference:'IEEE 754-2019，IEEE Standard for Floating-Point Arithmetic。',note:'免费页面提供标准信息，规范正文访问权限以 IEEE 为准。'},
 {id:'softfloat',title:'Berkeley SoftFloat',subtitle:'建立浮点结果对照模型',authors:'John R. Hauser',year:'Release 3e · 2018',type:'开源实现',topic:'floating',source:'作者官网',access:'开源代码 / 文档',free:true,url:'https://www.jhauser.us/arithmetic/SoftFloat.html',summary:'使用 C 浮点实现作为结果对照，学习舍入模式、异常标志与格式转换。',focus:'对照 RTL 的格式与配置，先验证普通数，再覆盖边界、特殊值与舍入。',tags:['验证','C','参考模型','舍入','浮点'],reference:'Berkeley SoftFloat，Release 3e（2018 年 1 月）。',note:'使用前核对支持格式与目标平台行为；不能不加适配地作为所有低精度格式的模型。'},
 {id:'testfloat',title:'Berkeley TestFloat',subtitle:'浮点实现的测试辅助工具',authors:'John R. Hauser',year:'项目文档',type:'开源实现',topic:'floating',source:'作者官网',access:'开源代码 / 文档',free:true,url:'https://www.jhauser.us/arithmetic/TestFloat.html',summary:'为浮点实现提供测试支持，与 SoftFloat 和 HardFloat 学习配合使用。',focus:'理解生成输入、参考结果与被测实现的连接方式，关注舍入与异常覆盖。',tags:['TestFloat','验证','测试','SoftFloat'],reference:'Berkeley TestFloat，作者项目主页与发布文档。',note:'测试工具不是形式化完备证明；仍需设计相关的边界与协议测试。'},
 {id:'cvfpu',title:'CVFPU / FPnew',subtitle:'论文对应的 SystemVerilog 实现',authors:'OpenHW Foundation · 项目贡献者',year:'项目仓库',type:'开源实现',topic:'ppa',source:'官方 GitHub 仓库',access:'开源代码 / 文档',free:true,url:'https://github.com/openhwfoundation/cvfpu',summary:'沿模块配置与握手接口阅读参数化 FPU，连接论文架构与具体 RTL。',focus:'先看项目 README 与 docs，再跟踪顶层参数、运算单元和流水线接口。',tags:['SystemVerilog','RTL','FPnew','FPU','PPA'],reference:'openhwfoundation/cvfpu，项目官方仓库。',note:'代码持续更新；复现实验时应固定 commit、依赖、约束和工具版本。'},
 {id:'asa',title:'Application-Specific Arithmetic',subtitle:'从正确计算走向按需求优化',authors:'Florent de Dinechin · Martin Kumm',year:'2024',type:'教材',topic:'ppa',source:'Springer · 出版方',access:'购买 / 机构访问',free:false,url:'https://link.springer.com/book/10.1007/978-3-031-42808-1',summary:'围绕应用需求讨论格式、误差与算术结构，连接经典运算和专用硬件优化。',focus:'先读格式与误差分析，再选读位权求和、乘除法及浮点算子的专用化与融合。',tags:['教材','PPA','FPGA','位宽','融合','误差'],reference:'Springer，2024。DOI: 10.1007/978-3-031-42808-1。',note:'读者需将书中 FPGA 或专用结构的条件与自己的 ASIC / FPGA 目标区分。'},
 {id:'flopoco',title:'FloPoCo',subtitle:'探索精度与流水线的算术核生成器',authors:'Florent de Dinechin · Martin Kumm 等',year:'项目文档',type:'开源实现',topic:'ppa',source:'项目官网',access:'开源代码 / 文档',free:true,url:'https://flopoco.org/',summary:'通过参数化算术核生成，探索格式选择、精度与目标频率之间的关系。',focus:'选择一个简单算子，固定输入输出精度，再改变频率目标观察生成结构。',tags:['FPGA','VHDL','生成器','PPA','流水线'],reference:'FloPoCo，项目官网与算子文档。',note:'不同算子的格式和舍入约定需分别核对；生成器和生成代码的许可说明见官网。'},
 {id:'flopoco-paper',title:'Designing Custom Arithmetic Data Paths with FloPoCo',subtitle:'算术功能与自动流水线的分工',authors:'Florent de Dinechin · Bogdan Pasca',year:'2011',type:'论文',topic:'ppa',source:'作者主页 · 项目引用记录',access:'作者公开稿',free:true,url:'https://perso.citi-lab.fr/fdedinec/recherche/publis/2011-DaT-FloPoCo.pdf',evidence:'https://flopoco.org/',summary:'学习如何将算术功能设计与面向目标频率的流水线组织分开考虑。',focus:'观察算法表达、参数化生成与流水线构建的边界，再考虑如何复现实验。',tags:['FloPoCo','流水线','FPGA','PPA','VHDL'],reference:'IEEE Design & Test of Computers，28(4)，18–27，2011；书目按 FloPoCo 官网引用。',note:'链接为作者公开稿，稿件标题为 Custom Arithmetic Datapath Design for FPGAs using the FloPoCo Core Generator，与正式发表题名不同。'}
];
